"""
monitoring/api_server.py — FastAPI server for MARK III Dashboard

Exposes the internal state of the TradingEngine to a real-time web UI.
Runs in a separate thread.
"""
from __future__ import annotations

import logging
import threading
from typing import TYPE_CHECKING, Any, Dict, List

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from config import settings

if TYPE_CHECKING:
    from main import TradingEngine

# Disable uvicorn access logs to prevent console spam
logging.getLogger("uvicorn.access").setLevel(logging.WARNING)


class APIServer:
    def __init__(self, engine: TradingEngine):
        self.engine = engine
        self.app = FastAPI(title="MARK III Dashboard API")
        
        # CORS
        self.app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

        self._setup_routes()

    def _setup_routes(self):
        @self.app.get("/api/state")
        def get_state() -> Dict[str, Any]:
            """Returns the current state of the engine, account, and recent candles."""
            account = self.engine._connector.get_account_info()
            positions = self.engine._connector.get_open_positions(magic=settings.MAGIC_NUMBER)
            
            # Extract basic position info
            pos_list = []
            for p in positions:
                pos_list.append({
                    "ticket": p.ticket,
                    "symbol": p.symbol,
                    "type": "BUY" if p.type == 0 else "SELL",
                    "volume": p.volume,
                    "price_open": p.price_open,
                    "sl": p.sl,
                    "tp": p.tp,
                    "profit": p.profit
                })

            # Get recent candles for the charts (last 30 for performance)
            cached_data = self.engine._data_provider.get_cached() if self.engine._data_provider else {}
            
            es_candles = []
            if "ES" in cached_data and "M5" in cached_data["ES"]:
                df_es = cached_data["ES"]["M5"]
                if self.engine._pseudo_delta:
                    import numpy as np
                    pressures = self.engine._pseudo_delta._candle_pressure(df_es)
                    cum_pressures = np.cumsum(pressures)
                    df_chart = df_es.copy()
                    df_chart["timestamp"] = df_chart["time"].astype("int64") // 10**9
                    df_chart["cumulative_delta"] = cum_pressures
                    es_candles = df_chart[-30:][["timestamp", "cumulative_delta"]].to_dict(orient="records")
                
            nq_candles = []
            if "NQ" in cached_data and "M5" in cached_data["NQ"]:
                df_nq = cached_data["NQ"]["M5"]
                if self.engine._pseudo_delta:
                    import numpy as np
                    pressures = self.engine._pseudo_delta._candle_pressure(df_nq)
                    cum_pressures = np.cumsum(pressures)
                    df_chart = df_nq.copy()
                    df_chart["timestamp"] = df_chart["time"].astype("int64") // 10**9
                    df_chart["cumulative_delta"] = cum_pressures
                    nq_candles = df_chart[-30:][["timestamp", "cumulative_delta"]].to_dict(orient="records")

            return {
                "account": {
                    "balance": self.engine.risk_manager._starting_balance if self.engine.risk_manager else account.get("balance", 0.0),
                    "equity": account.get("equity", 0.0),
                    "margin_free": account.get("margin_free", 0.0),
                },
                "engine": {
                    "mode": settings.TRADING_MODE,
                    "uptime_sec": self.engine.uptime_sec(),
                    "trades_today": self.engine.risk_manager.trades_today,
                    "max_trades": settings.MAX_TRADES_PER_DAY,
                },
                "positions": pos_list,
                "data": {
                    "ES": es_candles,
                    "NQ": nq_candles
                }
            }

        @self.app.get("/api/signals")
        def get_signals() -> List[Dict[str, Any]]:
            """Returns the recent signals generated by the engine."""
            # Engine needs a property to store recent signals
            if hasattr(self.engine, "recent_signals"):
                return [s.__dict__ for s in self.engine.recent_signals]
            return []

        @self.app.post("/api/close/{ticket}")
        def close_ticket(ticket: int):
            """Closes a specific MT5 ticket."""
            success = self.engine._order_manager.close_position(ticket, "MK3_Dashboard")
            if success:
                return {"status": "success", "message": f"Closed ticket {ticket}"}
            raise HTTPException(status_code=400, detail="Failed to close position or TRADING_MODE is SIGNAL")

        @self.app.post("/api/close_all")
        def close_all():
            """Closes all MARK III open positions."""
            count = self.engine._order_manager.close_all_positions()
            return {"status": "success", "message": f"Closed {count} positions"}

        # Serve static files for the dashboard
        import os
        static_dir = os.path.join(os.path.dirname(__file__), "dashboard")
        os.makedirs(static_dir, exist_ok=True)
        
        @self.app.get("/")
        def serve_index():
            return FileResponse(os.path.join(static_dir, "index.html"))

        self.app.mount("/static", StaticFiles(directory=static_dir), name="static")

    def run_in_background(self):
        """Starts the uvicorn server in a daemon thread."""
        def _run():
            uvicorn.run(
                self.app, 
                host=settings.DASHBOARD_HOST, 
                port=settings.DASHBOARD_PORT, 
                log_level="warning"
            )

        t = threading.Thread(target=_run, name="APIServer", daemon=True)
        t.start()
        return t
